// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event-states": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "get event-states",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "get event-states",
                "parameters": [
                    {
                        "type": "string",
                        "description": "comma seperated list of event-ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EventStates"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/events/{id}": {
            "head": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "check event",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "check event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/health": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "check service health",
                "tags": [
                    "health"
                ],
                "summary": "health",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/process-deployments": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "deploy process, meant for internal use by the process-deployment service, only admins may access this endpoint",
                "tags": [
                    "deployment"
                ],
                "summary": "deploy process",
                "parameters": [
                    {
                        "description": "deployment",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Deployment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/process-deployments/{userid}/{deplid}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "delete deployment, meant for internal use by the process-deployment service, only admins may access this endpoint",
                "tags": [
                    "deployment"
                ],
                "summary": "delete deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment id",
                        "name": "deplid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "userid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.EventStates": {
            "type": "object",
            "additionalProperties": {
                "type": "boolean"
            }
        },
        "deploymentmodel.ConditionalEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "qos": {
                    "type": "integer"
                },
                "script": {
                    "type": "string"
                },
                "selection": {
                    "$ref": "#/definitions/deploymentmodel.Selection"
                },
                "value_variable": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "deploymentmodel.Device": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.DeviceGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Diagram": {
            "type": "object",
            "properties": {
                "svg": {
                    "type": "string"
                },
                "xml_deployed": {
                    "type": "string"
                },
                "xml_raw": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Element": {
            "type": "object",
            "properties": {
                "bpmn_id": {
                    "type": "string"
                },
                "conditional_event": {
                    "$ref": "#/definitions/deploymentmodel.ConditionalEvent"
                },
                "group": {
                    "type": "string"
                },
                "message_event": {
                    "$ref": "#/definitions/deploymentmodel.MessageEvent"
                },
                "name": {
                    "type": "string"
                },
                "notification": {
                    "$ref": "#/definitions/deploymentmodel.Notification"
                },
                "order": {
                    "type": "integer"
                },
                "task": {
                    "$ref": "#/definitions/deploymentmodel.Task"
                },
                "time_event": {
                    "$ref": "#/definitions/deploymentmodel.TimeEvent"
                }
            }
        },
        "deploymentmodel.FilterCriteria": {
            "type": "object",
            "properties": {
                "aspect_id": {
                    "type": "string"
                },
                "characteristic_id": {
                    "description": "TODO: remove?",
                    "type": "string"
                },
                "device_class_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.GenericEventSource": {
            "type": "object",
            "properties": {
                "filter_ids": {
                    "type": "string"
                },
                "filter_type": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.IncidentHandling": {
            "type": "object",
            "properties": {
                "notify": {
                    "type": "boolean"
                },
                "restart": {
                    "type": "boolean"
                }
            }
        },
        "deploymentmodel.MessageEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "flow_id": {
                    "type": "string"
                },
                "selection": {
                    "$ref": "#/definitions/deploymentmodel.Selection"
                },
                "use_marshaller": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Notification": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.ProcessStartParameter": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Selection": {
            "type": "object",
            "properties": {
                "filter_criteria": {
                    "$ref": "#/definitions/deploymentmodel.FilterCriteria"
                },
                "selected_device_group_id": {
                    "type": "string"
                },
                "selected_device_id": {
                    "type": "string"
                },
                "selected_generic_event_source": {
                    "$ref": "#/definitions/deploymentmodel.GenericEventSource"
                },
                "selected_import_id": {
                    "type": "string"
                },
                "selected_path": {
                    "$ref": "#/definitions/deviceselectionmodel.PathOption"
                },
                "selected_service_id": {
                    "type": "string"
                },
                "selection_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deploymentmodel.SelectionOption"
                    }
                }
            }
        },
        "deploymentmodel.SelectionOption": {
            "type": "object",
            "properties": {
                "device": {
                    "$ref": "#/definitions/deploymentmodel.Device"
                },
                "device_group": {
                    "$ref": "#/definitions/deploymentmodel.DeviceGroup"
                },
                "import": {
                    "$ref": "#/definitions/importmodel.Import"
                },
                "importType": {
                    "$ref": "#/definitions/importmodel.ImportType"
                },
                "path_options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/deviceselectionmodel.PathOption"
                        }
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deploymentmodel.Service"
                    }
                }
            }
        },
        "deploymentmodel.Service": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Task": {
            "type": "object",
            "properties": {
                "parameter": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "prefer_event": {
                    "type": "boolean"
                },
                "retries": {
                    "type": "integer"
                },
                "selection": {
                    "$ref": "#/definitions/deploymentmodel.Selection"
                }
            }
        },
        "deploymentmodel.TimeEvent": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "devicemodel.AspectNode": {
            "type": "object",
            "properties": {
                "ancestor_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "child_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "descendent_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "root_id": {
                    "type": "string"
                }
            }
        },
        "deviceselectionmodel.Configurable": {
            "type": "object",
            "properties": {
                "aspect_node": {
                    "$ref": "#/definitions/devicemodel.AspectNode"
                },
                "characteristic_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "deviceselectionmodel.PathOption": {
            "type": "object",
            "properties": {
                "aspectNode": {
                    "$ref": "#/definitions/devicemodel.AspectNode"
                },
                "characteristicId": {
                    "type": "string"
                },
                "configurables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deviceselectionmodel.Configurable"
                    }
                },
                "functionId": {
                    "type": "string"
                },
                "isVoid": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "importmodel.Import": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/importmodel.ImportConfig"
                    }
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "import_type_id": {
                    "type": "string"
                },
                "kafka_topic": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "restart": {
                    "type": "boolean"
                }
            }
        },
        "importmodel.ImportConfig": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "importmodel.ImportContentVariable": {
            "type": "object",
            "properties": {
                "aspect_id": {
                    "type": "string"
                },
                "characteristic_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sub_content_variables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/importmodel.ImportContentVariable"
                    }
                },
                "type": {
                    "type": "string"
                },
                "use_as_tag": {
                    "type": "boolean"
                }
            }
        },
        "importmodel.ImportType": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/importmodel.ImportConfig"
                    }
                },
                "default_restart": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "output": {
                    "$ref": "#/definitions/importmodel.ImportContentVariable"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "model.Deployment": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "diagram": {
                    "$ref": "#/definitions/deploymentmodel.Diagram"
                },
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deploymentmodel.Element"
                    }
                },
                "executable": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "incident_handling": {
                    "$ref": "#/definitions/deploymentmodel.IncidentHandling"
                },
                "name": {
                    "type": "string"
                },
                "start_parameter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deploymentmodel.ProcessStartParameter"
                    }
                },
                "userId": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Event-Deployment",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
