basePath: /
definitions:
  api.EventStates:
    additionalProperties:
      type: boolean
    type: object
  model.Deployment:
    properties:
      description:
        type: string
      diagram:
        $ref: '#/definitions/models.Diagram'
      elements:
        items:
          $ref: '#/definitions/models.Element'
        type: array
      executable:
        type: boolean
      id:
        type: string
      incident_handling:
        $ref: '#/definitions/models.IncidentHandling'
      name:
        type: string
      start_parameter:
        items:
          $ref: '#/definitions/models.ProcessStartParameter'
        type: array
      userId:
        type: string
      version:
        type: integer
    type: object
  models.AspectNode:
    properties:
      ancestor_ids:
        items:
          type: string
        type: array
      aspect_class_id:
        type: string
      child_ids:
        items:
          type: string
        type: array
      descendent_ids:
        items:
          type: string
        type: array
      id:
        type: string
      name:
        type: string
      parent_id:
        type: string
      root_id:
        type: string
    type: object
  models.ConditionalEvent:
    properties:
      event_id:
        type: string
      qos:
        type: integer
      script:
        type: string
      selection:
        $ref: '#/definitions/models.Selection'
      value_variable:
        type: string
      variables:
        additionalProperties:
          type: string
        type: object
    type: object
  models.Configurable:
    properties:
      aspect_node:
        $ref: '#/definitions/models.AspectNode'
      characteristic_id:
        type: string
      function_id:
        type: string
      path:
        type: string
      type:
        type: string
      value: {}
    type: object
  models.Diagram:
    properties:
      svg:
        type: string
      xml_deployed:
        type: string
      xml_raw:
        type: string
    type: object
  models.Element:
    properties:
      bpmn_id:
        type: string
      conditional_event:
        $ref: '#/definitions/models.ConditionalEvent'
      group:
        type: string
      message_event:
        $ref: '#/definitions/models.MessageEvent'
      name:
        type: string
      notification:
        $ref: '#/definitions/models.Notification'
      order:
        type: integer
      task:
        $ref: '#/definitions/models.Task'
      time_event:
        $ref: '#/definitions/models.TimeEvent'
    type: object
  models.GenericEventSource:
    properties:
      filter_ids:
        type: string
      filter_type:
        type: string
      topic:
        type: string
    type: object
  models.Import:
    properties:
      configs:
        items:
          $ref: '#/definitions/models.ImportConfig'
        type: array
      id:
        type: string
      image:
        type: string
      import_type_id:
        type: string
      kafka_topic:
        type: string
      name:
        type: string
      restart:
        type: boolean
    type: object
  models.ImportConfig:
    properties:
      name:
        type: string
      value: {}
    type: object
  models.ImportContentVariable:
    properties:
      aspect_id:
        type: string
      characteristic_id:
        type: string
      function_id:
        type: string
      name:
        type: string
      sub_content_variables:
        items:
          $ref: '#/definitions/models.ImportContentVariable'
        type: array
      type:
        $ref: '#/definitions/models.Type'
      use_as_tag:
        type: boolean
    type: object
  models.ImportType:
    properties:
      configs:
        items:
          $ref: '#/definitions/models.ImportConfig'
        type: array
      default_restart:
        type: boolean
      description:
        type: string
      id:
        type: string
      image:
        type: string
      name:
        type: string
      output:
        $ref: '#/definitions/models.ImportContentVariable'
      owner:
        type: string
    type: object
  models.IncidentHandling:
    properties:
      notify:
        type: boolean
      restart:
        type: boolean
    type: object
  models.MessageEvent:
    properties:
      event_id:
        type: string
      flow_id:
        type: string
      selection:
        $ref: '#/definitions/models.Selection'
      use_marshaller:
        type: boolean
      value:
        type: string
    type: object
  models.Notification:
    properties:
      message:
        type: string
      title:
        type: string
    type: object
  models.PathOption:
    properties:
      aspectNode:
        $ref: '#/definitions/models.AspectNode'
      characteristicId:
        type: string
      configurables:
        items:
          $ref: '#/definitions/models.Configurable'
        type: array
      functionId:
        type: string
      isVoid:
        type: boolean
      path:
        type: string
      type:
        type: string
      value: {}
    type: object
  models.ProcessFilterCriteria:
    properties:
      aspect_id:
        description: 'deprecated: please use AspectIds'
        type: string
      aspect_ids:
        items:
          type: string
        type: array
      characteristic_id:
        type: string
      device_class_id:
        type: string
      function_id:
        type: string
    type: object
  models.ProcessStartParameter:
    properties:
      default:
        type: string
      id:
        type: string
      label:
        type: string
      properties:
        additionalProperties:
          type: string
        type: object
      type:
        type: string
    type: object
  models.Selection:
    properties:
      filter_criteria:
        $ref: '#/definitions/models.ProcessFilterCriteria'
      selected_device_group_id:
        type: string
      selected_device_id:
        type: string
      selected_generic_event_source:
        $ref: '#/definitions/models.GenericEventSource'
      selected_import_id:
        type: string
      selected_path:
        $ref: '#/definitions/models.PathOption'
      selected_service_id:
        type: string
      selection_options:
        items:
          $ref: '#/definitions/models.SelectionOption'
        type: array
    type: object
  models.SelectionDevice:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.SelectionDeviceGroup:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.SelectionOption:
    properties:
      device:
        $ref: '#/definitions/models.SelectionDevice'
      device_group:
        $ref: '#/definitions/models.SelectionDeviceGroup'
      import:
        $ref: '#/definitions/models.Import'
      importType:
        $ref: '#/definitions/models.ImportType'
      path_options:
        additionalProperties:
          items:
            $ref: '#/definitions/models.PathOption'
          type: array
        type: object
      services:
        items:
          $ref: '#/definitions/models.SelectionService'
        type: array
    type: object
  models.SelectionService:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.Task:
    properties:
      parameter:
        additionalProperties:
          type: string
        type: object
      prefer_event:
        type: boolean
      retries:
        type: integer
      selection:
        $ref: '#/definitions/models.Selection'
    type: object
  models.TimeEvent:
    properties:
      time:
        type: string
      type:
        type: string
    type: object
  models.Type:
    enum:
    - https://schema.org/Text
    - https://schema.org/Integer
    - https://schema.org/Float
    - https://schema.org/Boolean
    - https://schema.org/ItemList
    - https://schema.org/StructuredValue
    type: string
    x-enum-varnames:
    - String
    - Integer
    - Float
    - Boolean
    - List
    - Structure
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Event-Deployment
  version: "0.1"
paths:
  /device-groups/{id}:
    post:
      description: update event-deployments of device-group, meant for internal use
        by the process-deployment service, only admins may access this endpoint
      parameters:
      - description: device-group id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: update event-deployments of device-group
      tags:
      - deployment
  /event-states:
    get:
      description: get event-states
      parameters:
      - description: comma seperated list of event-ids
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.EventStates'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: get event-states
      tags:
      - event
  /events/{id}:
    head:
      description: check event
      parameters:
      - description: event id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: check event
      tags:
      - event
  /health:
    post:
      description: check service health
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: health
      tags:
      - health
  /process-deployments:
    put:
      description: deploy process, meant for internal use by the process-deployment
        service, only admins may access this endpoint
      parameters:
      - description: deployment
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.Deployment'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: deploy process
      tags:
      - deployment
  /process-deployments/{userid}/{deplid}:
    delete:
      description: delete deployment, meant for internal use by the process-deployment
        service, only admins may access this endpoint
      parameters:
      - description: deployment id
        in: path
        name: deplid
        required: true
        type: string
      - description: user id
        in: path
        name: userid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - Bearer: []
      summary: delete deployment
      tags:
      - deployment
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
